# Generated by Django 2.1.7 on 2019-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('publication_date', models.DateTimeField()),
                ('message_id', models.IntegerField()),
                ('link', models.URLField(null=True)),
            ],
            options={
                'ordering': ('publication_date',),
            },
        ),
    ]
